spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football
    username: packt
    password: packt
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false